import dayjs from 'dayjs';
import { ICatalogueValue } from 'app/shared/model/catalogue-value.model';
import { IRUser } from 'app/shared/model/r-user.model';
import { ICandidateRelocationPreference } from 'app/shared/model/candidate-relocation-preference.model';
import { SalaryTimeSpan } from 'app/shared/model/enumerations/salary-time-span.model';
import { CandidateRelocationType } from 'app/shared/model/enumerations/candidate-relocation-type.model';

export interface ICandidate {
  id?: number;
  salutation?: string | null;
  firstName?: string | null;
  middleName?: string | null;
  lastName?: string | null;
  email?: string | null;
  altEmails?: string | null;
  phone?: string | null;
  altPhones?: string | null;
  dob?: string | null;
  nationality?: string | null;
  workAuthorizationId?: number | null;
  address?: string | null;
  area?: string | null;
  city?: string | null;
  state?: string | null;
  stateCode?: string | null;
  county?: string | null;
  country?: string | null;
  countryCode?: string | null;
  zipCode?: string | null;
  source?: string | null;
  totalExpInYears?: number | null;
  totalExpInMonths?: number | null;
  relevantExpInYears?: number | null;
  relevantExpInMonths?: number | null;
  referredBy?: string | null;
  ownershipUserId?: number | null;
  currentJobTitle?: string | null;
  currentEmployer?: string | null;
  currentJobTypeId?: number | null;
  currentPayCurrency?: string | null;
  currentPay?: number | null;
  currentPayMonthly?: number | null;
  currentPayHourly?: number | null;
  currentPayYearly?: number | null;
  currentPayTimeSpan?: SalaryTimeSpan | null;
  otherCurrentBenefits?: string | null;
  expectedPayCurrency?: string | null;
  expectedPayMin?: number | null;
  expectedPayMax?: number | null;
  expectedPayMinMonthly?: number | null;
  expectedPayMinHourly?: number | null;
  expectedPayMinYearly?: number | null;
  expectedPayMaxMonthly?: number | null;
  expectedPayMaxHourly?: number | null;
  expectedPayMaxYearly?: number | null;
  expectedPayTimeSpan?: SalaryTimeSpan | null;
  expectedPayTaxTermId?: number | null;
  otherExpectedBenefits?: string | null;
  additionalComments?: string | null;
  relocation?: boolean | null;
  familyWillingToRelocate?: boolean | null;
  relocationType?: CandidateRelocationType | null;
  relocationRemarks?: string | null;
  taxTermIds?: string | null;
  noticePeriodInDays?: number | null;
  workAuthorizationExpiry?: string | null;
  gpa?: string | null;
  aadharNumber?: string | null;
  linkedInProfileURL?: string | null;
  otherSocialURLs?: string | null;
  tags?: string | null;
  resumes?: string | null;
  rightToReperesent?: string | null;
  skills?: string | null;
  altSkills?: string | null;
  technologies?: string | null;
  certifications?: string | null;
  languages?: string | null;
  workExperience?: string | null;
  education?: string | null;
  employerDetails?: string | null;
  documents?: string | null;
  workAuthorization?: ICatalogueValue | null;
  ownershipUser?: IRUser | null;
  currentJobType?: ICatalogueValue | null;
  expectedPayTaxTerm?: ICatalogueValue | null;
  candidateRelocationPreferences?: ICandidateRelocationPreference[] | null;
}

export const defaultValue: Readonly<ICandidate> = {
  relocation: false,
  familyWillingToRelocate: false,
};
