import dayjs from 'dayjs';
import { ITeam } from 'app/shared/model/team.model';
import { IBusinessUnit } from 'app/shared/model/business-unit.model';
import { IClient } from 'app/shared/model/client.model';
import { ICatalogueValue } from 'app/shared/model/catalogue-value.model';
import { IRuser } from 'app/shared/model/ruser.model';
import { IContact } from 'app/shared/model/contact.model';
import { IJobLocation } from 'app/shared/model/job-location.model';
import { IJobDocument } from 'app/shared/model/job-document.model';
import { IJobCustomAttribute } from 'app/shared/model/job-custom-attribute.model';
import { SalaryTimeSpan } from 'app/shared/model/enumerations/salary-time-span.model';
import { JobApplicationForm } from 'app/shared/model/enumerations/job-application-form.model';
import { JobStatus } from 'app/shared/model/enumerations/job-status.model';
import { RemoteJob } from 'app/shared/model/enumerations/remote-job.model';

export interface IJob {
  id?: number;
  title?: string | null;
  jobCode?: string | null;
  clientJobCode?: string | null;
  orgName?: string | null;
  orgEmploymentTypeIds?: string | null;
  jobRef?: string | null;
  jobSource?: string | null;
  url?: string | null;
  description?: string | null;
  publicJobTitle?: string | null;
  publicJobDescription?: string | null;
  autoCloseDate?: string | null;
  noOfPositions?: number | null;
  departmentAltText?: string | null;
  displayCandRate?: boolean | null;
  candRateCurrency?: string | null;
  candMinRate?: number | null;
  candMaxRate?: number | null;
  candRateTimeSpan?: SalaryTimeSpan | null;
  candRateTaxTerm?: string | null;
  candSalaryAltDisplayText?: string | null;
  otherBenefitDetails?: string | null;
  clientBillRateCurrency?: string | null;
  clientBillRate?: number | null;
  clientBillRateTimeSpan?: SalaryTimeSpan | null;
  clientBillRateTaxTerm?: string | null;
  workDuration?: string | null;
  immigrationStatus?: string | null;
  displayImmigrationStatus?: string | null;
  skills?: string | null;
  altSkills?: string | null;
  tags?: string | null;
  qualificationIds?: string | null;
  qualificationsAltText?: string | null;
  eduRequirements?: string | null;
  expRequirements?: string | null;
  expAltText?: string | null;
  minExpInYears?: number | null;
  maxExpInYears?: number | null;
  languageIds?: string | null;
  visaRequirements?: string | null;
  workAuthorizationIds?: string | null;
  applicationFormType?: JobApplicationForm | null;
  isPartnerJob?: boolean | null;
  redirectionUrl?: string | null;
  jobStatus?: JobStatus | null;
  endClient?: string | null;
  domainAlt?: string | null;
  comments?: string | null;
  additionalNotificationsToUserIds?: string | null;
  additionalNotificationsToTeamIds?: string | null;
  requiredDocumentIds?: string | null;
  jobCloseReasonOtherAlt?: string | null;
  addToCareerPage?: boolean | null;
  remoteJob?: RemoteJob | null;
  hiringFor?: string | null;
  workDurationTimeSpan?: string | null;
  taxTerms?: string | null;
  postedByTeam?: ITeam | null;
  businessUnit?: IBusinessUnit | null;
  client?: IClient | null;
  jobType?: ICatalogueValue | null;
  industry?: ICatalogueValue | null;
  department?: ICatalogueValue | null;
  clientRecruiter?: IRuser | null;
  clientManager?: IContact | null;
  accountManager?: IRuser | null;
  headOfRecruitment?: IRuser | null;
  deliveryLeadManager?: IRuser | null;
  domain?: ICatalogueValue | null;
  srDeliveryManager?: IRuser | null;
  teamLead?: IRuser | null;
  priority?: ICatalogueValue | null;
  jobCloseReason?: ICatalogueValue | null;
  jobCategory?: ICatalogueValue | null;
  jobOccupation?: ICatalogueValue | null;
  jobLocations?: IJobLocation[] | null;
  jobDocuments?: IJobDocument[] | null;
  jobCustomAttributes?: IJobCustomAttribute[] | null;
}

export const defaultValue: Readonly<IJob> = {
  displayCandRate: false,
  isPartnerJob: false,
  addToCareerPage: false,
};
